user route test, subscriber service, schema test
ShahzaibParacha/COMP-4350-Project pull request #134
Opened 2023-03-14 17:21 UTC by WeiyuSun

1. user(include subscriber) route and controller test
2. subscriber service and schema test
3. one bug find: for the endpoint /user/subscription/setNotification, The request type is POST. But I use Request Parameter to handle the parameters. I have changed to request body. see the code details

2023-03-14 18:14 UTC, DaTanUmanitoba commented
Sure, I will write the tests for notification for subscribers.

2023-03-14 18:31 UTC, DaTanUmanitoba submitted a review, later dismissed
It seems all good.

2023-03-14 22:00 UTC, ShahzaibParacha requested changes

2023-03-14 22:00 UTC, ShahzaibParacha commented on backend/middleware/user-middleware.js
> +    let creatorId = req.body.creator_id
all else looks good, I think @orangeboy55555 will need to approve if this needs to be body or query

2023-03-15 05:55 UTC, orangeboy55555 commented on backend/middleware/user-middleware.js
> +    let creatorId = req.body.creator_id
I think it should be query since GET requests don't have a body.

2023-03-15 05:56 UTC, orangeboy55555 requested changes
I think you should delete the unreachable code. They want 100% code coverage XD

2023-03-16 04:49 UTC, DaTanUmanitoba approved these changes
seems all good to merge

2023-03-16 04:56 UTC, orangeboy55555 approved these changes
Looks good

2023-03-16 06:11 UTC, ShahzaibParacha approved these changes

2023-03-16 06:19 UTC, merged