Dt/feature/post-controller-update
ShahzaibParacha/COMP-4350-Project pull request #135
Opened 2023-03-14 22:54 UTC by DaTanUmanitoba

modify the GET method of post-controller to the correct format, and paying debts for the related tests

add new data to the res body

2023-03-14 23:09 UTC, ShahzaibParacha approved these changes

2023-03-14 23:11 UTC, orangeboy55555 requested changes

2023-03-14 23:11 UTC, orangeboy55555 commented on backend/controller/post-controller.js
> +            result.push({username: user.username, affiliation: user.affiliation, numberLikes: likes})
I think Shahzaib wants the profile picture as well.

2023-03-14 23:14 UTC, ShahzaibParacha commented on backend/controller/post-controller.js
> +            result.push({username: user.username, affiliation: user.affiliation, numberLikes: likes})
true

2023-03-15 00:12 UTC, orangeboy55555 approved these changes
Looks good

2023-03-15 00:21 UTC, ShahzaibParacha approved these changes
looks good now

2023-03-15 00:21 UTC, merged